is_debug: true
listen:
  type: port
  port: 3003
storage:
  host: localhost
  port: 5432
  database: toleg
  username: postgres
  password: 12345
  pg_pool_max_conn: 10
jwt_key: normalnybol!!!
socket_jwt_key: normalnybol!!!
app_version: 0.0.1
max_file_size: 10485760
public_path: /../../public


email_port: 587
email_host : smtp.gmail.com
